
insert into `candidate`
(student_no,
 dbscert_number,
 fastatus,
 ftpchecked,
 ucascardiff_course_code,
 application_status_code,
 application_status_comments,
 application_statushcare,
 cardiff_course_code,
 confirmation_comments,
 contextual_flag,
 correspondence_lang_welsh,
 country_of_domicile,
 date_of_birth,
 date_received,
 enrolment_criteria_comments,
 entry_year,
 essential_to_dos,
 fee_status,
 fee_status_comments,
 first_name,
 gender,
 grades_achieved,
 grades_achieved_after,
 highest_level_qualification,
 home_email,
 interview_date,
 interview_invite_comments,
 invite_interview,
 issue_date,
 keeping_warm_email_sent,
 latest_decision_code,
 nationality,
 non_standard_qualifications_chaser_email,
 offer_conditions,
 offer_email_sent,
 personalid,
 record_first_created,
 surname,
 total_interview_score,
 total_personal_statement_score,
 update_service,
 welsh_speaker)
values
    ('01932678',
     '',
     '',
     0,
     'B720',
     1,
     '',
     'CFUF',
     'UFBWMIDA',
     '',
     1,
     0,
     'England',
     DATE '1983-03-03',
     '23.11.17',
     '',
     '2018/9',
     '',
     0,
     '',
     'Richard',
     0,
     '',
     '',
     '',
     'N/A',
     DATE '2018-01-09',
     '',
     0,
     '',
     0,
     'CODE',
     'UNITED KINGDOM',
     null,
     '',
     1,
     '1167890123',
     DATE '2007-11-23',
     'EKONG',
     50,
     60,
     '',
     0);


insert into `candidate`
(student_no,
 dbscert_number,
 fastatus,
 ftpchecked,
 ucascardiff_course_code,
 application_status_code,
 application_status_comments,
 application_statushcare,
 cardiff_course_code,
 confirmation_comments,
 contextual_flag,
 correspondence_lang_welsh,
 country_of_domicile,
 date_of_birth,
 date_received,
 enrolment_criteria_comments,
 entry_year,
 essential_to_dos,
 fee_status,
 fee_status_comments,
 first_name,
 gender,
 grades_achieved,
 grades_achieved_after,
 highest_level_qualification,
 home_email,
 interview_date,
 interview_invite_comments,
 invite_interview,
 issue_date,
 keeping_warm_email_sent,
 latest_decision_code,
 nationality,
 non_standard_qualifications_chaser_email,
 offer_conditions,
 offer_email_sent,
 personalid,
 record_first_created,
 surname,
 total_interview_score,
 total_personal_statement_score,
 update_service,
 welsh_speaker)
values
    ('01932679',
     '',
     '',
     1,
     'B720',
     0,
     '',
     'CFUF',
     'UFBWMIDA',
     '',
     0,
     1,
     'Germany',
     DATE '1989-01-03',
     '28.11.17',
     '',
     '2018/9',
     '',
     1,
     '',
     'Adele',
     1,
     '',
     '',
     '',
     'N/A',
     DATE '2018-01-09',
     '',
     1,
     '',
     1,
     'CODE',
     'UNITED KINGDOM',
     null,
     '',
     1,
     '1167890124',
     DATE '2007-11-24',
     'Barry',
     50,
     45,
     '',
     0);

insert into `managed_user`(username, password, user_role) values ('Richard','password','USER');

insert into `managed_user`(username, password, user_role) values ('Faisal','password','USER');

insert into `managed_user`(username, password, user_role) values ('Bhatt','password','USER');

insert into `managed_user`(username, password, user_role) values ('Yinzou','password','USER');

insert into `managed_user`(username, password, user_role) values ('Yibo','password','USER');

insert into `managed_user`(username, password, user_role) values ('Admin','password','ADMIN');

